language: rust
sudo: required

rust:
  - stable
  - nightly
os: linux
matrix:
  fast_finish: true
services:
  - docker

cache: cargo

script:
  - if [ -z "$TRAVIS_TAG" ]; then cargo test --all; fi
before_deploy:
  - ./ci/build-release.sh dip ${TRAVIS_TAG}-${TRAVIS_OS_NAME}

deploy:
  - provider: releases
    api_key: $AUTH_TOKEN
    file_glob: true
    file:
      - dip-*
    on:
      condition: $TRAVIS_RUST_VERSION = stable
      tags: true
    skip_cleanup: true

