[package]
name = "dip"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]

[dependencies]
failure = "0.1"
hyper = "0.12"
lazy_static = "1.1"
notify = "4.0"
regex = "1.0"
structopt = "0.2"
toml = "0.4"
walkdir = "2.2"
